/*
 * generated by Xtext
 */
package at.ac.tuwien.big.forms.form.scoping;

import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import at.ac.tuwien.big.forms.Attribute;
import at.ac.tuwien.big.forms.AttributePageElement;
import at.ac.tuwien.big.forms.AttributeType;
import at.ac.tuwien.big.forms.AttributeValueCondition;
import at.ac.tuwien.big.forms.Column;
import at.ac.tuwien.big.forms.Entity;
import at.ac.tuwien.big.forms.Feature;
import at.ac.tuwien.big.forms.Form;
import at.ac.tuwien.big.forms.Relationship;
import at.ac.tuwien.big.forms.RelationshipPageElement;
import at.ac.tuwien.big.forms.SelectionField;
import at.ac.tuwien.big.forms.Table;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class FormScopeProvider extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider {

	public IScope scope_AttributePageElement_attribute(AttributePageElement pageElement, EReference reference) {
		if (pageElement instanceof SelectionField) {
			return scope_SelectionField_attribute((SelectionField) pageElement, reference);
		} else if (pageElement instanceof Column) {
			return scope_Column_attribute((Column) pageElement, reference);
		}
		
		Form form = getForm(pageElement);
		return Scopes.scopeFor(getAttributes(form.getEntity()));
	}
	
	public IScope scope_RelationshipPageElement_relationship(RelationshipPageElement pageElement, EReference reference) {
		Form form = getForm(pageElement);
		return Scopes.scopeFor(getRelationships(form.getEntity()));
	}
	
	public IScope scope_AttributeValueCondition_attribute(AttributeValueCondition attributeValueCondition, EReference eReference) { 
		Form form = getForm(attributeValueCondition);
		return Scopes.scopeFor(getAttributes(form.getEntity()));	
	}
	
	public IScope scope_Column_attribute(Column column, EReference eReference){
		Table table = (Table) column.eContainer();
		Form form = table.getEditingForm();
		return Scopes.scopeFor(getAttributes(form.getEntity()));
	}
	
	public IScope scope_SelectionField_attribute(SelectionField selectionField, EReference eReference){
		Form form = getForm(selectionField);
		Collection<Attribute> attributes = getAttributes(form.getEntity());
		Iterator<Attribute> iter = attributes.iterator();
		
		while(iter.hasNext()) {
			Attribute attribute = iter.next();
			if (attribute.getType() != AttributeType.BOOLEAN && attribute.getEnumeration() == null) {
				iter.remove();
			}
		}
		
		return Scopes.scopeFor(attributes);
	}
	
	private Form getForm(EObject object) {
		while (object != null && !(object instanceof Form)) {
			object = object.eContainer();
		}
		
		return (Form) object;
	}
	
	private Collection<Attribute> getAttributes(Entity entity) {
		Entity currentEntity = entity;
		Collection<Attribute> attributes = new HashSet<Attribute>();

		while(currentEntity != null){
			for (Feature feature : currentEntity.getFeatures()) {
				if(feature instanceof Attribute){
					attributes.add((Attribute) feature);
				}
			}
			
			currentEntity = currentEntity.getSuperType();
		}
		
		return attributes;
	}
	
	private Collection<Relationship> getRelationships(Entity entity) {
		Entity currentEntity = entity;
		Collection<Relationship> relationships = new HashSet<Relationship>();

		while(currentEntity != null){
			for (Feature feature : currentEntity.getFeatures()) {
				if(feature instanceof Relationship){
					relationships.add((Relationship) feature);
				}
			}
			
			currentEntity = currentEntity.getSuperType();
		}
		
		return relationships;
	}

}
